// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        ASpin: typeof import('ant-design-vue/es')['Spin']
        Axis: typeof import('../src/components/d3-charts/axis.vue')['default']
        Button: typeof import('../src/components/button/button.vue')['default']
        D3Map: typeof import('../src/components/d3Map.vue')['default']
        D3MapOld: typeof import('../src/components/d3Map-old.vue')['default']
        GridLine: typeof import('../src/components/d3-charts/gridLine.vue')['default']
        Lines: typeof import('../src/components/d3-charts/lines.vue')['default']
        Loading: typeof import('../src/components/loading.vue')['default']
        Pie: typeof import('../src/components/d3-charts/pie.vue')['default']
        PieNew: typeof import('../src/components/d3-charts/pie-new.vue')['default']
        PreviewModal: typeof import('../src/components/preview-modal.vue')['default']
        Process: typeof import('../src/components/d3-charts/process.vue')['default']
        RectAxis: typeof import('../src/components/d3-charts/rectAxis.vue')['default']
        RectAxisNew: typeof import('../src/components/d3-charts/rectAxis-new.vue')['default']
        Ring: typeof import('../src/components/d3-charts/ring.vue')['default']
        SvgIcon: typeof import('../src/components/svg-icon/svg-icon.vue')['default']
        Tooltip: typeof import('../src/components/tooltip.vue')['default']
    }
}

export {}
